### ISSUE TITLE
PaperPanel: inlcude more lables in search

### ISSUE THREAD

**Issue by jarasch** [covidgraph/visual-graph-explorer#16]
Could we include the following labels in the paper search:
'Paper'
'Abstract'
'Title'

**Comment by yGuy** [comment]
Definitely, we can adjust to use the a different full-text query and search all of them at once, or have a dropdown or checkboxes for searching in fulltext, abstract, title, only - what would you prefer?

**Comment by yGuy** [comment]
With the new full-text search - is this still something that we should improve or are you happy with the current state? Just let me know.
