### ISSUE TITLE
Positioning of search buttons?

### ISSUE THREAD

**Issue by Jiros** [covidgraph/visual-graph-explorer#34]
Is it possible to move the 'Find ...' buttons (particularly for the Gene  - Publications search) as the multi-select auto-populate result panel covers the button and it's not immediately obvious how to hide it again. Not an issue for any of the single value fields as the auto-populate disappears after you select an option.

![gene - publication search.png](https://images.zenhubusercontent.com/5e999dc3ead6800cb49587e0/8804a431-c2c6-44c9-bc7a-1e6711ad37cf)

**Comment by yGuy** [comment]
With the new integrated search UI, this one is actually not valid anymore, I guess. We can always reopen, though.
