### ISSUE TITLE
Missmatch of result count in DB and App

### ISSUE THREAD

**Issue by motey** [covidgraph/visual-graph-explorer#35]
When searching for e.g. `diabetes` in a publication title in the DB 

```cypher
MATCH (n:Paper) 
WHERE n.title contains 'diabetes' RETURN count(n)
```
The result count is `286` (as for 29.07.2020 on PROD)

When searching for `diabetes` in the App i get only 10 results
![image](https://user-images.githubusercontent.com/1006417/88792463-8b92a100-d19b-11ea-9015-fbf8438fab5c.png)

is this a bug or expected?

**Comment by yGuy** [comment]
That's a hard-coded limit and in this case is far too low. Ideally we should have a way to sort the search results by importance - currently we just cut-off the results: 
https://github.com/covidgraph/visual-graph-explorer/blob/9d7893fbd4b3ab18fb635d54dc78084d3ee47bfa/src/util/CovidGraphLoader.js#L41

I increased the limit to 250 for now - (it was literally "10") for some of the search queries which of course is way too low.
