### ISSUE TITLE
Including properies for node labels

### ISSUE THREAD

**Issue by jarasch** [covidgraph/visual-graph-explorer#45]
The following properties would be interesting to display in the visual graph explorer

**Patent:**
- "Patent Title": MATCH (p:Patent)-[:PATENT_HAS_PATENTTITLE]->(title:PatentTitle{text:'...some title'})
- "type": "Patent Application",
- "pub_key": "CA_3041165_A1"
- "pub_date": "2018-04-26",
- "filing_key": "CA_3041165_A_20171020",
- "filing_date": "2017-10-20",
- "jurisdiction": "CA",
- "lens_url": "https://lens.org/197-921-240-414-415",
- "Patent owner": MATCH (p:Patent)-[:INVENTOR]->(e:Entity)

**Disease:**
- "name": "anterior ischemic optic neuropathy",
- "link": "http://www.disease-ontology.org/?id=DOID:12010",

**Protein:**
- "sid": "ACE2"
- "source": "RefSeq"
- Other identifiers: MATCH(p:Protein)-[:MAPS]-(others:Protein)

**Anatomy:**
- "mesh_name": "Nose",
- "mesh_id": "D009666",
- "name": "nose",
- "uberon_id": "UBERON:0000004"

**Disease:**
- "name": "anterior ischemic optic neuropathy",
- "link": "http://www.disease-ontology.org/?id=DOID:12010",
- "license": "CC0 1.0",
- "doid": "DOID:12010",
- "source": "http://www.disease-ontology.org"

**Affiliation:**
- "institution": "Hong Kong Special Administrative Region",
- "laboratory": "",

**Entities:**
- "name": "Novartis"
- "filed patents": MATCH(e:Entity)<-[:INVENTOR]-(p:Patent)

**Comment by yGuy** [comment]
![image](https://user-images.githubusercontent.com/2486305/101158926-df6f3400-362c-11eb-86fa-137f1d30cdb4.png)

Done!
